version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: synapmentor-backend
    ports:
      - "8081:8081"
    environment:
      - ENV=development
      - DB_PATH=/app/data/synapmentor.db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=8081
    volumes:
      - backend_data:/root/data
    networks:
      - synapmentor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: synapmentor-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - synapmentor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: synapmentor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - synapmentor-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Nginx reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    container_name: synapmentor-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - synapmentor-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  backend_data:
    driver: local
  redis_data:
    driver: local

networks:
  synapmentor-network:
    driver: bridge
