version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: synapmentor-backend
    ports:
      - "8081:8081"
    environment:
      - ENV=development
      - DB_PATH=/app/data/synapmentor.db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=8081
    volumes:
      - backend_data:/root/data:Z
    networks:
      - synapmentor-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: synapmentor-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - synapmentor-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=50m
      - /var/run:rw,noexec,nosuid,size=10m

  redis:
    image: redis:7-alpine
    container_name: synapmentor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data:Z
    networks:
      - synapmentor-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    security_opt:
      - no-new-privileges:true
    user: "999:999"

volumes:
  backend_data:
    driver: local
  redis_data:
    driver: local

networks:
  synapmentor-network:
    driver: bridge
