# Jenkins Pipeline Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-pipeline-config
  namespace: jenkins
data:
  # Pipeline configuration
  pipeline.properties: |
    # Build configuration
    BUILD_TIMEOUT=30
    TEST_TIMEOUT=15
    DEPLOY_TIMEOUT=10
    
    # Image registry configuration
    REGISTRY_URL=your-registry.com
    REGISTRY_NAMESPACE=synapmentor
    
    # Kubernetes configuration
    STAGING_NAMESPACE=staging
    PRODUCTION_NAMESPACE=production
    
    # Notification configuration
    SLACK_CHANNEL_DEPLOYMENTS=#deployments
    SLACK_CHANNEL_ALERTS=#alerts
    
    # Security scanning
    TRIVY_SEVERITY=HIGH,CRITICAL
    SONAR_PROJECT_KEY=synapmentor
    
  # Quality gates
  quality-gates.yaml: |
    coverage:
      backend:
        minimum: 80
        target: 90
      frontend:
        minimum: 75
        target: 85
    
    security:
      max_critical_vulnerabilities: 0
      max_high_vulnerabilities: 5
      
    performance:
      max_build_time_minutes: 30
      max_test_time_minutes: 15
      
  # Deployment strategies
  deployment-strategy.yaml: |
    staging:
      strategy: rolling
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
          
    production:
      strategy: blue-green
      replicas: 3
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
          
  # Environment-specific configurations
  environments.yaml: |
    staging:
      domain: staging.synapmentor.com
      database:
        type: sqlite
        backup: enabled
      monitoring:
        enabled: true
        retention: 7d
        
    production:
      domain: synapmentor.com
      database:
        type: sqlite
        backup: enabled
        retention: 30d
      monitoring:
        enabled: true
        retention: 30d
        alerting: enabled
