# Default values for synapmentor
# This is a YAML-formatted file.

# Global configuration
global:
  imageRegistry: "your-registry.com"
  imagePullSecrets:
    - synapmentor-registry-secret

# Environment configuration
environment: production

# Backend configuration
backend:
  enabled: true
  image:
    repository: synapmentor-backend
    tag: latest
    pullPolicy: Always
  
  replicaCount: 3
  
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  
  env:
    ENV: production
    PORT: "8081"
    DB_PATH: "/app/data/synapmentor.db"
    LOG_LEVEL: "info"
  
  secrets:
    JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
    DB_ENCRYPTION_KEY: "your-db-encryption-key"
  
  persistence:
    enabled: true
    storageClass: "fast-ssd"
    size: 10Gi
    accessMode: ReadWriteOnce
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

# Frontend configuration
frontend:
  enabled: true
  image:
    repository: synapmentor-frontend
    tag: latest
    pullPolicy: Always
  
  replicaCount: 3
  
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
    fsGroup: 101
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
  
  hosts:
    - host: synapmentor.com
      paths:
        - path: /api
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend
    - host: www.synapmentor.com
      paths:
        - path: /api
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend
  
  tls:
    - secretName: synapmentor-tls-secret
      hosts:
        - synapmentor.com
        - www.synapmentor.com

# Redis configuration (optional)
redis:
  enabled: false
  auth:
    enabled: true
    password: "redis-password"
  master:
    persistence:
      enabled: true
      size: 8Gi

# PostgreSQL configuration (optional, for future migration from SQLite)
postgresql:
  enabled: false
  auth:
    postgresPassword: "postgres-password"
    database: "synapmentor"
  primary:
    persistence:
      enabled: true
      size: 20Gi

# Monitoring configuration
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
  
  grafana:
    enabled: true
    adminPassword: "admin-password"
  
  prometheus:
    enabled: true
    retention: 15d

# Network policies
networkPolicy:
  enabled: true
  ingress:
    enabled: true
  egress:
    enabled: true

# Pod disruption budgets
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Security policies
podSecurityPolicy:
  enabled: true

# Node affinity and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

# Pod annotations
podAnnotations: {}

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""
